<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$ledgerPath = $root . '/docs/php85-negative-boundaries.json';
$data = json_decode(file_get_contents($ledgerPath), true, flags: JSON_THROW_ON_ERROR);
$fixtureRoot = $root . '/tests/fixtures/php/8.5/';
$counts = $areas = $categories = $productions = [];
$hashes = ['ledger' => hash_file('sha256', $ledgerPath), 'grammar' => hash_file('sha256', $root . '/grammar/8.5/php.ebnf')];
foreach (['valid', 'invalid', 'contextual-invalid'] as $kind) {
    $files = [...glob($fixtureRoot . $kind . '/*.php'), ...glob($fixtureRoot . 'short-tags-disabled/' . $kind . '/*.php')];
    $counts[$kind] = count($files);
    foreach ($files as $file) $hashes[substr($file, strlen($fixtureRoot))] = hash_file('sha256', $file);
}
foreach ($data['known_discrepancies'] as $row) {
    $hashes[$row['fixture']] = hash_file('sha256', $fixtureRoot . $row['fixture']);
}
ksort($hashes);
foreach ($data['cases'] as $row) {
    $kind = $row['classification'];
    $areas[$row['area']][$kind] = ($areas[$row['area']][$kind] ?? 0) + 1;
    $categories[$row['category']][$kind] = ($categories[$row['category']][$kind] ?? 0) + 1;
    $productions[$row['production']] = true;
}
ksort($areas);
ksort($categories);
$text = "# PHP 8.5 negative-boundary ledger\n\n";
$text .= "Generated by `php tools/php85-negative-report.php`; verify with `--check`.\n";
$text .= "Edit [php85-negative-boundaries.json](php85-negative-boundaries.json) and fixtures, then regenerate.\n\n";
$text .= "Input digest (ledger, grammar, and corpus bytes): `" . hash('sha256', json_encode($hashes, JSON_THROW_ON_ERROR)) . "`.\n\n";
$text .= $data['method'] . "\n\n";
$text .= "A production is an anchor for the boundary, not a claim that its every alternative or combination has a rejection witness.\n";
$text .= "Structural-negative means repository recognition and PHP lint must reject. Contextual-negative means repository recognition must accept and PHP lint must reject.\n";
$text .= "Positive repairs must pass both. Existing contextual fixtures are reviewed separately below.\n\n";
$text .= "Corpus across both short-tag profiles: **{$counts['valid']} valid, {$counts['invalid']} structural-negative, {$counts['contextual-invalid']} contextual-negative**.\n";
$text .= count($data['known_discrepancies']) . " known discrepancies remain outside these ordinary counts.\n\n";
$text .= count($data['cases']) . " Phase 4 boundary pairs anchor " . count($productions) . " distinct productions.\n\n";
foreach (['Syntax area' => $areas, 'Boundary category' => $categories] as $title => $table) {
    $text .= "| $title | Structural-negative pairs | Contextual-negative pairs |\n|---|---:|---:|\n";
    foreach ($table as $name => $row) {
        $text .= '| ' . $name . ' | ' . ($row['structural-negative'] ?? 0) . ' | ' . ($row['contextual-negative'] ?? 0) . " |\n";
    }
    $text .= "\n";
}
$text .= "## Paired evidence\n\n";
$text .= "Source references identify productions or compiler functions at PHP source pin `{$data['source_pin']}`; see [sources](sources.md).\n\n";
$text .= "| Boundary / negative fixture | Positive repair | Production anchor | Classification | Category | Source |\n|---|---|---|---|---|---|\n";
foreach ($data['cases'] as $row) {
    $text .= "| [{$row['id']}](../tests/fixtures/php/8.5/{$row['negative']}) | [repair](../tests/fixtures/php/8.5/{$row['positive']}) | `{$row['production']}` | {$row['classification']} | {$row['category']} | {$row['evidence']} |\n";
}
$text .= "\n## Contextual-negative review\n\n";
$text .= "Every current contextual-negative fixture remains structural acceptance evidence, never EBNF rejection evidence.\n";
$text .= "PHP compilation is the differential contextual check; a complete repository-owned contextual validator is not implemented.\n\n";
$text .= "| Fixture | Restriction | Decision | Source |\n|---|---|---|---|\n";
foreach ($data['contextual_review'] as $row) {
    $text .= "| [" . basename($row['fixture']) . "](../tests/fixtures/php/8.5/{$row['fixture']}) | {$row['restriction']} | {$row['reason']} | {$row['evidence']} |\n";
}
$text .= "\n## Known discrepancies\n\n";
if ($data['known_discrepancies'] === []) {
    $text .= "No confirmed acceptance differential is currently recorded. Exhaustive conformance remains unproven; see the parser/compiler remediation report.\n";
}
foreach ($data['known_discrepancies'] as $row) {
    $text .= "- [{$row['restriction']}](../tests/fixtures/php/8.5/{$row['fixture']}): {$row['disposition']} Owner: {$row['owner']}. Evidence: {$row['evidence']}.\n";
}
$path = $root . '/docs/php85-negative-boundaries.md';
if (in_array('--check', $argv, true)) {
    if (!is_file($path) || file_get_contents($path) !== $text) {
        fwrite(STDERR, "Negative-boundary report is stale. Run php tools/php85-negative-report.php\n");
        exit(1);
    }
} else {
    file_put_contents($path, $text);
}
echo json_encode(['corpus' => $counts, 'boundary_pairs' => count($data['cases']), 'production_anchors' => count($productions), 'areas' => $areas], JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR) . "\n";
